// esp32:esp32@3.3.11 çekirdeğiyle birlikte gelen kütüphaneler — canlı builder
// konteynerinde /opt/arduino/data/packages/esp32/hardware/esp32/3.3.11/libraries
// içinden sayıldı (bkz. docs/backend.plan.md §8 Adım 4). Kurulum gerektirmez,
// panelde salt-okunur bir grup olarak gösterilir. Core sürümü değişirse bu
// liste de elden güncellenmeli.
export const BUNDLED_LIBRARIES: readonly string[] = [
  'ArduinoOTA',
  'AsyncUDP',
  'BLE',
  'BluetoothSerial',
  'Console',
  'DNSServer',
  'EEPROM',
  'ESP32',
  'ESP_HostedOTA',
  'ESP_I2S',
  'ESP_NOW',
  'ESP_SR',
  'ESP_Video',
  'ESPmDNS',
  'Ethernet',
  'FFat',
  'FS',
  'HTTPClient',
  'HTTPUpdate',
  'HTTPUpdateServer',
  'Hash',
  'Insights',
  'LittleFS',
  'Matter',
  'NetBIOS',
  'Network',
  'NetworkClientSecure',
  'OpenThread',
  'PPP',
  'Preferences',
  'RainMaker',
  'SD',
  'SD_MMC',
  'SPI',
  'SPIFFS',
  'SimpleBLE',
  'Ticker',
  'USB',
  'Update',
  'WebServer',
  'WiFi',
  'WiFiProv',
  'Wire',
  'Zigbee',
];
